defaults:
  - _self_
  - task: square_image

name: train_bet_image
_target_: diffusion_policy.workspace.train_bet_hybrid_image_workspace.TrainBETHybridImageWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 3
n_obs_steps: 3
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_cond: True
pred_action_steps_only: False

policy:
  _target_: diffusion_policy.policy.bet_hybrid_image_policy.BETHybridImagePolicy

  shape_meta: ${shape_meta}

  action_ae:
    _target_: diffusion_policy.model.bet.action_ae.discretizers.k_means.KMeansDiscretizer
    num_bins: 24
    action_dim: ${shape_meta.action.shape[0]}
    predict_offsets: True

  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  # image
  crop_shape: [76, 76]
  obs_encoder_group_norm: False
  eval_fixed_crop: false

  # arch
  obs_as_cond: True
  n_layer: 4
  n_head: 4
  n_embed: 72
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  vocab_size: ${policy.action_ae.num_bins}
  predict_offsets: True
  offset_loss_scale: 1000.0
  focal_loss_gamma: 2.0
  discrete_input: False


dataloader:
  batch_size: 64
  num_workers: 1
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 1
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  learning_rate: 0.0001 # 1e-4
  weight_decay: 0.1
  betas: [0.9, 0.95]

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 10
  num_epochs: 200
  gradient_accumulate_every: 1
  grad_norm_clip: 1.0
  enable_normalizer: True
  # training loop control
  # in epochs
  rollout_every: 20
  checkpoint_every: 20
  val_every: 1
  sample_every: 10
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: BeT_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
