defaults:
  - _self_
  - task: square_image

name: train_vinn_byol_image
_target_: diffusion_policy.workspace.train_vinn_byol_workspace.TrainVINNByolImageWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 1
n_obs_steps: 1
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False

policy:
  _target_: diffusion_policy.policy.vinn_byol_policy.VINNBoylImagePolicy

  net:
    _target_: torchvision.models.resnet50

    pretrained: True

  image_size: 76
  hidden_layer: avgpool
  projection_size: 256
  projection_hidden_size: 4096
  moving_average_decay: 0.99
  use_momentum: True

  shape_meta: ${shape_meta}
  horizon: ${horizon}
  crop_shape: [76, 76]
  top_k: 50

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  num_epochs: 100
  gradient_accumulate_every: 1
  rollout_every: 10
  checkpoint_every: 10
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

optimizer:
  learning_rate: 1.0e-4
  betas: [0.9, 0.95]

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

logging:
  project: vinn_byol_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}