defaults:
  - _self_
  - task: square_image
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: train_our_byol_policy_workspace
_target_: diffusion_policy.workspace.train_our_policy_workspace.TrainOurPolicyWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 1
n_obs_steps: 1
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False

policy:
  _target_: diffusion_policy.policy.our_policy.OurPolicy

  shape_meta: ${shape_meta}

  discretizer:
    _target_: diffusion_policy.model.our_model.discretizer.k_means.KMeansDiscretizer

    feature_dim: 1000
    num_bins: 10
    n_iter: 100
    predict_offsets: False
  
  byol:
    _target_: diffusion_policy.model.our_model.byol.byol.pretrain_model

    image_size: 76
    hidden_layer: 'avgpool'
    projection_size: 256
    projection_hidden_size: 4096
    moving_average_decay: 0.99
    use_momentum: True
    pretrain: True
  
  byol_path: diffusion_policy/model/our_model/byol/state_dict/latest_epoch90.pt
  byol_channels: 1

  transformer:
    _target_: diffusion_policy.model.ACT.transformer.Transformer
    d_model: 512
    nhead: 8
    num_encoder_layers: 4
    num_decoder_layers: 4
    dim_feedfowrard: 2048
    dropout: 0.1
    activation: relu
    normalize_before: False
    return_intermediate_dec: False
  trans_encoder_layer:
    _target_: diffusion_policy.model.ACT.transformer.TransformerEncoderLayer
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    activation: relu
    normalize_before: False

  num_encoder_layers: 4
  center_point_dim: 1
  num_queries: 10
  camera_names: ["agentview_image"]
  kl_weights: 10
  temporal_agg: True
  state_dim: 7



training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  # optimization
  lr_scheduler: cosine
  # Transformer needs lr wormup
  lr_warmup_steps: 100
  num_epochs: 1000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epcoch
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 10
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

optimizer:
  weight_decay: 1.0e-4
  learning_rate: 1.0e-4
  betas: [0.9, 0.95]

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

logging:
  project: train_resnet50_with_byol
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${task_name}", "${name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}